plugins {
    id 'application'
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.th2.component)
}

group = 'com.exactpro.th2'
version = release_version

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.th2.common) {
        exclude group: 'com.exactpro.th2', module: 'task-utils'
    }
    implementation(libs.th2.common.utils)

    implementation(libs.kotlin.logging)

    implementation(libs.rawhttp.core)
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    compileOnly(libs.auto.service)
    kapt(libs.auto.service)

    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation(libs.junit.jupiter.integration)
    testImplementation(libs.strikt.core)
    testImplementation(libs.strikt.jackson)
}

test {
    useJUnitPlatform {
        excludeTags('integration-test')
    }
}

tasks.register('integrationTest', Test) {
    group = 'verification'
    useJUnitPlatform {
        includeTags('integration-test')
    }
}

application {
    mainClass = 'com.exactpro.th2.http.client.Main'
}